# Dependencies
gems: [jekyll-paginate, jekyll-gist, rouge]
kramdown:         
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Datascience for Docs
tagline:          A practical introduction with an emphasis on critical care
description:      ""
url:              http://datascibc.github.io/course/
baseurl:          /

author:
  name:           'Steve Harris'
  url:            https://twitter.com/datascibc

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/datascibc/course